name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "luajit"]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@v4

    - name: build
      run: |
        luarocks install rocks-sysdetect --dev

    - name: test
      run: |
        luarocks test spec/sysdetect_spec.lua
